name: spotify
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  rxdart: ^0.21.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/Spotify_Logo.png
   - assets/images/Spooftify_Logo.png
   - assets/images/player1.png
   - assets/images/player2.png
   - assets/images/artists/Ariana_Grande.jpg
   - assets/images/artists/Billie_Eilish.jpg
   - assets/images/artists/Cardi_B.jpg
   - assets/images/artists/Charli_XCX.jpg
   - assets/images/artists/CHVRCHES.jpg
   - assets/images/artists/Drake.jpg
   - assets/images/artists/Halsey.jpg
   - assets/images/artists/Hayden_James.jpg
   - assets/images/artists/Kanye_West.jpg
   - assets/images/artists/Lana_Del_Rey.jpg
   - assets/images/artists/London_Grammar.jpg
   - assets/images/artists/Lorde.jpg
   - assets/images/artists/Madeon.jpg
   - assets/images/artists/Marina.jpg
   - assets/images/artists/Nicki_Minaj.jpg
   - assets/images/artists/Petit_Biscuit.jpg
   - assets/images/artists/Sigrid.jpg
   - assets/images/artists/Sky_Ferreira.jpg
   - assets/images/artists/Superpoze.jpg
   - assets/images/artists/Travis_Scott.jpg
   - assets/images/podcasts/arts_entertainement.png
   - assets/images/podcasts/comedy.png
   - assets/images/podcasts/educational.png
   - assets/images/podcasts/lifestyle_health.png
   - assets/images/podcasts/music.png
   - assets/images/podcasts/news_politics.png
   - assets/images/podcasts/sports_recreation.png
   - assets/images/podcasts/stories.png
   - assets/images/podcasts/top_podcasts.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
